application:
  actions: actions
  web: false
  runtimeManifest:
    packages:
      sling-da:
        license: Apache-2.0
        actions:
          gettoken:
            function: actions/gettoken/index.js
            web: false
            runtime: nodejs:18
            inputs:
              ADOBE_CLIENT_ID: $SERVICE_API_KEY
              ADOBE_CLIENT_SECRET: $ADOBE_CLIENT_SECRET
              ADOBE_TARGET_SCOPES: $AIO_ims_contexts_Credential__in__AEM__Target__Integration__Sling__YP_scopes
              LOG_LEVEL: debug
            annotations:
              final: true
              require-adobe-auth: false
            limits:
              timeout: 60000
              memorySize: 1024

          exportoffers:
            function: actions/exportoffers/index.js
            web: true
            runtime: nodejs:18
            inputs:
              ADOBE_CLIENT_ID: $SERVICE_API_KEY
              ADOBE_TARGET_TENANT: 'acssandboxusone'
              LOG_LEVEL: debug
            annotations:
              final: true
              require-adobe-auth: false
            limits:
              timeout: 60000
              memorySize: 1024